FORMAT: 1A
HOST: https://ride-my-way-server.herokuapp.com/api/v1

# Ride My Way 

Ride-My-Way is a carpooling application that provides drivers with the ability to create ride offers and passengers to join available ride offers.

## User [/auth]

### Create a New user [POST]
You may create a new user using this action. It takes a JSON
object containing user details and sends back a response message and token object.

+ Request (application/json)

        {
           "firstname": "Gift",
           "lastname": "Egwuenu",
           "email": "laurandidi21@gmail.com",
           "location": "Lagos",
           "password": "123456"
        }

+ Response 201 (application/json)

    + Headers

            Location: /auth/signup

    + Body

            {
                "message": "User registration successful",
                "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MzA0MzY3MzUsImV4cCI6MTUzMDUyMzEzNX0.d-vggC0oDk9dfGQDzYCZQ7Pqj__1tyC6JjQ1cspa69g"
            }
            
+ Response 400 (application/json)

    + Headers

            Location: /auth/signup

    + Body

            {
                "message": "Please provide a  valid firstname",
                "token": null
            }