const db = [
  {
    id: 1,
    location: 'Surulere',
    destination: 'Ajah',
    seats: 3,
    price: 3000,
    driver: 'John',
    riders: ['Timi', 'Gift'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    location: 'Victoria Island',
    destination: 'Ojudu Berger',
    seats: 1,
    price: 300,
    driver: 'John',
    riders: ['Timi', 'Gift'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    location: 'Ikeja',
    destination: 'Oshodi',
    seats: 2,
    price: 2000,
    driver: 'John',
    riders: ['Timi', 'Gift'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 4,
    location: 'Maryland',
    destination: 'Mile 2',
    seats: 1,
    price: 500,
    driver: 'John',
    riders: ['Timi', 'Gift'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export default db;
